### ISSUE TITLE
Use static analysis tools

### ISSUE THREAD

**Issue by gnumoksha** [gnumoksha/php-freeipa#12]
Setup [phpstan](https://github.com/phpstan/phpstan) and [psalm](https://github.com/vimeo/psalm).

**Comment by davidribeiro** [comment]
@gnumoksha if you need any help I can try to do this
from what I understand, you just want to add both phpstan and psalm to the project's dev dependencies, right?

**Comment by gnumoksha** [comment]
Hi, @davidribeiro. Thanks for helping!

This task for static analyzers should be done in the sequence described in the [TODO list](https://github.com/gnumoksha/php-freeipa/projects/1). It is part of a complete rewrite of this library.

Shortly I will push a new branch with the new code.
