### ISSUE TITLE
How to install/run the latest version of php-freeipa

### ISSUE THREAD

**Issue by jpanda001** [gnumoksha/php-freeipa#26]
Hi, since there is no bootstrap.php and autoload.php in the latest version of this application, can u give me an example of how I can install and  run this package. Thanks in advance

**Comment by gnumoksha** [comment]
Hi

The v1 is not finished yet. You should use [v0](https://github.com/gnumoksha/php-freeipa/tree/v0).

But if you want to try the v1, do the following:
- Download composer https://getcomposer.org/download/
- Run `composer init`
- Install the latest version of package `php-http/curl-client`
- Install the `dev-master` version of package `gnumoksha/php-freeipa`
- Create the connection like in
```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

use Gnumoksha\FreeIpa\FreeIpa;
use Gnumoksha\FreeIpa\Options;
use Gnumoksha\FreeIpa\Infra\Rpc\Request\CommonBody;

// https://ipa.demo1.freeipa.org/ipa/config/ca.crt
$freeIpa = new FreeIpa(
            new Options(
                'ipa.demo1.freeipa.org',
                __DIR__ . '/ca.crt'
            )
        );

$freeIpa->login('admin', 'Secret123');

$response = $freeIpa->sendRequest(new CommonBody('ping'));

var_dump($response);
```
